#ifndef LAUNCHER_THEME_H
#define LAUNCHER_THEME_H

#define LAUNCHER_COLOR_TEXT      0xFFFF
#define LAUNCHER_COLOR_HIGHLIGHT 0xFFE0
#define LAUNCHER_COLOR_BG        0x0012
#define LAUNCHER_COLOR_BORDER    0xFFFF

#define LAUNCHER_LOGO_X          140
#define LAUNCHER_LOGO_Y          18

#define LAUNCHER_MAIN_ITEM0_X    164
#define LAUNCHER_MAIN_ITEM0_Y    130
#define LAUNCHER_MAIN_ITEM1_X    164
#define LAUNCHER_MAIN_ITEM1_Y    174
#define LAUNCHER_MAIN_ITEM2_X    164
#define LAUNCHER_MAIN_ITEM2_Y    218

#define LAUNCHER_MAIN_INFO_X     70
#define LAUNCHER_MAIN_INFO_Y     304
#define LAUNCHER_MAIN_VALUE_X    70
#define LAUNCHER_MAIN_VALUE_Y    334

#define LAUNCHER_HINT1_X         52
#define LAUNCHER_HINT1_Y         388
#define LAUNCHER_HINT2_X         52
#define LAUNCHER_HINT2_Y         414

#define LAUNCHER_BROWSER_TITLE_X 146
#define LAUNCHER_BROWSER_TITLE_Y 24
#define LAUNCHER_BROWSER_PATH_X  24
#define LAUNCHER_BROWSER_PATH_Y  72
#define LAUNCHER_BROWSER_LIST_X  28
#define LAUNCHER_BROWSER_LIST_Y  110
#define LAUNCHER_BROWSER_STEP_Y  24
#define LAUNCHER_BROWSER_ROWS    11

#define LAUNCHER_OPTIONS_TITLE_X 214
#define LAUNCHER_OPTIONS_TITLE_Y 28
#define LAUNCHER_OPTIONS_INFO_X  170
#define LAUNCHER_OPTIONS_INFO_Y  170
#define LAUNCHER_OPTIONS_BACK_X  236
#define LAUNCHER_OPTIONS_BACK_Y  220

#endif
